//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klijent.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServis")]
    public interface IServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/LogovanjeKorisnika", ReplyAction="http://tempuri.org/IServis/LogovanjeKorisnikaResponse")]
        bool LogovanjeKorisnika(string korisnickoIme, string sifra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/LogovanjeKorisnika", ReplyAction="http://tempuri.org/IServis/LogovanjeKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> LogovanjeKorisnikaAsync(string korisnickoIme, string sifra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistrovanjeKorisnika", ReplyAction="http://tempuri.org/IServis/RegistrovanjeKorisnikaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClassLibrary.Izuzetak), Action="http://tempuri.org/IServis/RegistrovanjeKorisnikaIzuzetakFault", Name="Izuzetak", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
        bool RegistrovanjeKorisnika(string korisnickoIme, string lozinka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistrovanjeKorisnika", ReplyAction="http://tempuri.org/IServis/RegistrovanjeKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> RegistrovanjeKorisnikaAsync(string korisnickoIme, string lozinka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistovanjeClana", ReplyAction="http://tempuri.org/IServis/RegistovanjeClanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClassLibrary.Izuzetak), Action="http://tempuri.org/IServis/RegistovanjeClanaIzuzetakFault", Name="Izuzetak", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
        bool RegistovanjeClana(ClassLibrary.Clan clan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistovanjeClana", ReplyAction="http://tempuri.org/IServis/RegistovanjeClanaResponse")]
        System.Threading.Tasks.Task<bool> RegistovanjeClanaAsync(ClassLibrary.Clan clan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistrovanjePisca", ReplyAction="http://tempuri.org/IServis/RegistrovanjePiscaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClassLibrary.Izuzetak), Action="http://tempuri.org/IServis/RegistrovanjePiscaIzuzetakFault", Name="Izuzetak", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
        bool RegistrovanjePisca(ClassLibrary.Pisac pisac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistrovanjePisca", ReplyAction="http://tempuri.org/IServis/RegistrovanjePiscaResponse")]
        System.Threading.Tasks.Task<bool> RegistrovanjePiscaAsync(ClassLibrary.Pisac pisac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistrovanjeKnjige", ReplyAction="http://tempuri.org/IServis/RegistrovanjeKnjigeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClassLibrary.Izuzetak), Action="http://tempuri.org/IServis/RegistrovanjeKnjigeIzuzetakFault", Name="Izuzetak", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
        bool RegistrovanjeKnjige(ClassLibrary.Knjiga knjiga, uint kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/RegistrovanjeKnjige", ReplyAction="http://tempuri.org/IServis/RegistrovanjeKnjigeResponse")]
        System.Threading.Tasks.Task<bool> RegistrovanjeKnjigeAsync(ClassLibrary.Knjiga knjiga, uint kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/IznajmiKnjigu", ReplyAction="http://tempuri.org/IServis/IznajmiKnjiguResponse")]
        bool IznajmiKnjigu(ClassLibrary.Clan clan, ClassLibrary.Knjiga knjiga, int id_knjige);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/IznajmiKnjigu", ReplyAction="http://tempuri.org/IServis/IznajmiKnjiguResponse")]
        System.Threading.Tasks.Task<bool> IznajmiKnjiguAsync(ClassLibrary.Clan clan, ClassLibrary.Knjiga knjiga, int id_knjige);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/VratiKnjigu", ReplyAction="http://tempuri.org/IServis/VratiKnjiguResponse")]
        bool VratiKnjigu(int id_knjige, int id_iznajmljivanja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/VratiKnjigu", ReplyAction="http://tempuri.org/IServis/VratiKnjiguResponse")]
        System.Threading.Tasks.Task<bool> VratiKnjiguAsync(int id_knjige, int id_iznajmljivanja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/IznajmljeneKnjigeClana", ReplyAction="http://tempuri.org/IServis/IznajmljeneKnjigeClanaResponse")]
        System.Data.DataSet IznajmljeneKnjigeClana(ulong jmbg_clana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/IznajmljeneKnjigeClana", ReplyAction="http://tempuri.org/IServis/IznajmljeneKnjigeClanaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> IznajmljeneKnjigeClanaAsync(ulong jmbg_clana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/IzmenaVrednostiTabele", ReplyAction="http://tempuri.org/IServis/IzmenaVrednostiTabeleResponse")]
        bool IzmenaVrednostiTabele(string naziv_tabele, string naziv_kolone, string naziv_id_kolone, string id, string value_type, string vrednost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/IzmenaVrednostiTabele", ReplyAction="http://tempuri.org/IServis/IzmenaVrednostiTabeleResponse")]
        System.Threading.Tasks.Task<bool> IzmenaVrednostiTabeleAsync(string naziv_tabele, string naziv_kolone, string naziv_id_kolone, string id, string value_type, string vrednost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/PretragaBazePodataka", ReplyAction="http://tempuri.org/IServis/PretragaBazePodatakaResponse")]
        System.Data.DataSet PretragaBazePodataka(string keyword, System.Collections.Generic.Dictionary<string, bool> izbori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/PretragaBazePodataka", ReplyAction="http://tempuri.org/IServis/PretragaBazePodatakaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> PretragaBazePodatakaAsync(string keyword, System.Collections.Generic.Dictionary<string, bool> izbori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/DetaljnaPretragaClana", ReplyAction="http://tempuri.org/IServis/DetaljnaPretragaClanaResponse")]
        System.Data.DataSet DetaljnaPretragaClana(string ime, string prezime, string email, System.DateTime datum_rodjenja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/DetaljnaPretragaClana", ReplyAction="http://tempuri.org/IServis/DetaljnaPretragaClanaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DetaljnaPretragaClanaAsync(string ime, string prezime, string email, System.DateTime datum_rodjenja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/DetaljnaPretragaKnjige", ReplyAction="http://tempuri.org/IServis/DetaljnaPretragaKnjigeResponse")]
        System.Data.DataSet DetaljnaPretragaKnjige(string naziv, int kolicina, int godina_izdavanja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/DetaljnaPretragaKnjige", ReplyAction="http://tempuri.org/IServis/DetaljnaPretragaKnjigeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DetaljnaPretragaKnjigeAsync(string naziv, int kolicina, int godina_izdavanja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/DetaljnaPretragaPisca", ReplyAction="http://tempuri.org/IServis/DetaljnaPretragaPiscaResponse")]
        System.Data.DataSet DetaljnaPretragaPisca(string ime, string prezime, System.DateTime datum_rodjenja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/DetaljnaPretragaPisca", ReplyAction="http://tempuri.org/IServis/DetaljnaPretragaPiscaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DetaljnaPretragaPiscaAsync(string ime, string prezime, System.DateTime datum_rodjenja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SviClanovi", ReplyAction="http://tempuri.org/IServis/SviClanoviResponse")]
        System.Data.DataSet SviClanovi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SviClanovi", ReplyAction="http://tempuri.org/IServis/SviClanoviResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SviClanoviAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SviPisci", ReplyAction="http://tempuri.org/IServis/SviPisciResponse")]
        System.Data.DataSet SviPisci();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SviPisci", ReplyAction="http://tempuri.org/IServis/SviPisciResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SviPisciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SveKnjige", ReplyAction="http://tempuri.org/IServis/SveKnjigeResponse")]
        System.Data.DataSet SveKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SveKnjige", ReplyAction="http://tempuri.org/IServis/SveKnjigeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SveKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SvaIznajmljivanja", ReplyAction="http://tempuri.org/IServis/SvaIznajmljivanjaResponse")]
        System.Data.DataSet SvaIznajmljivanja();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServis/SvaIznajmljivanja", ReplyAction="http://tempuri.org/IServis/SvaIznajmljivanjaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SvaIznajmljivanjaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServisChannel : Klijent.ServiceReference.IServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServisClient : System.ServiceModel.ClientBase<Klijent.ServiceReference.IServis>, Klijent.ServiceReference.IServis {
        
        public ServisClient() {
        }
        
        public ServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogovanjeKorisnika(string korisnickoIme, string sifra) {
            return base.Channel.LogovanjeKorisnika(korisnickoIme, sifra);
        }
        
        public System.Threading.Tasks.Task<bool> LogovanjeKorisnikaAsync(string korisnickoIme, string sifra) {
            return base.Channel.LogovanjeKorisnikaAsync(korisnickoIme, sifra);
        }
        
        public bool RegistrovanjeKorisnika(string korisnickoIme, string lozinka) {
            return base.Channel.RegistrovanjeKorisnika(korisnickoIme, lozinka);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrovanjeKorisnikaAsync(string korisnickoIme, string lozinka) {
            return base.Channel.RegistrovanjeKorisnikaAsync(korisnickoIme, lozinka);
        }
        
        public bool RegistovanjeClana(ClassLibrary.Clan clan) {
            return base.Channel.RegistovanjeClana(clan);
        }
        
        public System.Threading.Tasks.Task<bool> RegistovanjeClanaAsync(ClassLibrary.Clan clan) {
            return base.Channel.RegistovanjeClanaAsync(clan);
        }
        
        public bool RegistrovanjePisca(ClassLibrary.Pisac pisac) {
            return base.Channel.RegistrovanjePisca(pisac);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrovanjePiscaAsync(ClassLibrary.Pisac pisac) {
            return base.Channel.RegistrovanjePiscaAsync(pisac);
        }
        
        public bool RegistrovanjeKnjige(ClassLibrary.Knjiga knjiga, uint kolicina) {
            return base.Channel.RegistrovanjeKnjige(knjiga, kolicina);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrovanjeKnjigeAsync(ClassLibrary.Knjiga knjiga, uint kolicina) {
            return base.Channel.RegistrovanjeKnjigeAsync(knjiga, kolicina);
        }
        
        public bool IznajmiKnjigu(ClassLibrary.Clan clan, ClassLibrary.Knjiga knjiga, int id_knjige) {
            return base.Channel.IznajmiKnjigu(clan, knjiga, id_knjige);
        }
        
        public System.Threading.Tasks.Task<bool> IznajmiKnjiguAsync(ClassLibrary.Clan clan, ClassLibrary.Knjiga knjiga, int id_knjige) {
            return base.Channel.IznajmiKnjiguAsync(clan, knjiga, id_knjige);
        }
        
        public bool VratiKnjigu(int id_knjige, int id_iznajmljivanja) {
            return base.Channel.VratiKnjigu(id_knjige, id_iznajmljivanja);
        }
        
        public System.Threading.Tasks.Task<bool> VratiKnjiguAsync(int id_knjige, int id_iznajmljivanja) {
            return base.Channel.VratiKnjiguAsync(id_knjige, id_iznajmljivanja);
        }
        
        public System.Data.DataSet IznajmljeneKnjigeClana(ulong jmbg_clana) {
            return base.Channel.IznajmljeneKnjigeClana(jmbg_clana);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IznajmljeneKnjigeClanaAsync(ulong jmbg_clana) {
            return base.Channel.IznajmljeneKnjigeClanaAsync(jmbg_clana);
        }
        
        public bool IzmenaVrednostiTabele(string naziv_tabele, string naziv_kolone, string naziv_id_kolone, string id, string value_type, string vrednost) {
            return base.Channel.IzmenaVrednostiTabele(naziv_tabele, naziv_kolone, naziv_id_kolone, id, value_type, vrednost);
        }
        
        public System.Threading.Tasks.Task<bool> IzmenaVrednostiTabeleAsync(string naziv_tabele, string naziv_kolone, string naziv_id_kolone, string id, string value_type, string vrednost) {
            return base.Channel.IzmenaVrednostiTabeleAsync(naziv_tabele, naziv_kolone, naziv_id_kolone, id, value_type, vrednost);
        }
        
        public System.Data.DataSet PretragaBazePodataka(string keyword, System.Collections.Generic.Dictionary<string, bool> izbori) {
            return base.Channel.PretragaBazePodataka(keyword, izbori);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PretragaBazePodatakaAsync(string keyword, System.Collections.Generic.Dictionary<string, bool> izbori) {
            return base.Channel.PretragaBazePodatakaAsync(keyword, izbori);
        }
        
        public System.Data.DataSet DetaljnaPretragaClana(string ime, string prezime, string email, System.DateTime datum_rodjenja) {
            return base.Channel.DetaljnaPretragaClana(ime, prezime, email, datum_rodjenja);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DetaljnaPretragaClanaAsync(string ime, string prezime, string email, System.DateTime datum_rodjenja) {
            return base.Channel.DetaljnaPretragaClanaAsync(ime, prezime, email, datum_rodjenja);
        }
        
        public System.Data.DataSet DetaljnaPretragaKnjige(string naziv, int kolicina, int godina_izdavanja) {
            return base.Channel.DetaljnaPretragaKnjige(naziv, kolicina, godina_izdavanja);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DetaljnaPretragaKnjigeAsync(string naziv, int kolicina, int godina_izdavanja) {
            return base.Channel.DetaljnaPretragaKnjigeAsync(naziv, kolicina, godina_izdavanja);
        }
        
        public System.Data.DataSet DetaljnaPretragaPisca(string ime, string prezime, System.DateTime datum_rodjenja) {
            return base.Channel.DetaljnaPretragaPisca(ime, prezime, datum_rodjenja);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DetaljnaPretragaPiscaAsync(string ime, string prezime, System.DateTime datum_rodjenja) {
            return base.Channel.DetaljnaPretragaPiscaAsync(ime, prezime, datum_rodjenja);
        }
        
        public System.Data.DataSet SviClanovi() {
            return base.Channel.SviClanovi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SviClanoviAsync() {
            return base.Channel.SviClanoviAsync();
        }
        
        public System.Data.DataSet SviPisci() {
            return base.Channel.SviPisci();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SviPisciAsync() {
            return base.Channel.SviPisciAsync();
        }
        
        public System.Data.DataSet SveKnjige() {
            return base.Channel.SveKnjige();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SveKnjigeAsync() {
            return base.Channel.SveKnjigeAsync();
        }
        
        public System.Data.DataSet SvaIznajmljivanja() {
            return base.Channel.SvaIznajmljivanja();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SvaIznajmljivanjaAsync() {
            return base.Channel.SvaIznajmljivanjaAsync();
        }
    }
}
